#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Discuz.Droid.Resource", IsApplication=true)]

namespace Discuz.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Discuz.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Discuz.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Discuz.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Discuz.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Discuz.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Discuz.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Discuz.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Discuz.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Discuz.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Discuz.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Discuz.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Discuz.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Discuz.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Discuz.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Discuz.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Discuz.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Discuz.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Discuz.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Discuz.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Discuz.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Discuz.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Discuz.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Discuz.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Discuz.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Discuz.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Discuz.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Discuz.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Discuz.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_mytheme = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_mytheme = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_mytheme = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_mytheme = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_mytheme = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_mytheme = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int arrow_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bottom = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_default_mytheme = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_focused_mytheme = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_mytheme = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_pressed_mytheme = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_bottom_mytheme = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cab_background_top_mytheme = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int favorite = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_errorstatus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_successstatus = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int list_focused_mytheme = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int list_pressed_mytheme = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int menu_dropdown_panel_mytheme = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_bg_mytheme = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_horizontal_mytheme = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_primary_mytheme = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_secondary_mytheme = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int refresh = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int roundedbg = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int roundedbgdark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int selectable_background_mytheme = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_default_mytheme = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_disabled_mytheme = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_focused_mytheme = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_ab_pressed_mytheme = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_background_ab_mytheme = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_indicator_ab_mytheme = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_focused_mytheme = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_mytheme = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_selected_pressed_mytheme = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_focused_mytheme = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_mytheme = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_unselected_pressed_mytheme = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int top = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int loadingImage = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int loadingProgressBar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int loadingProgressWheel = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int textViewStatus = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int ActionBar_Solid_Mytheme = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ActionBar_Transparent_Mytheme = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionBarTabStyle_Mytheme = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int ActionButton_CloseMode_Mytheme = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int DropDownListView_Mytheme = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int DropDownNav_Mytheme = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int PopupMenu_Mytheme = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int ProgressBar_Mytheme = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Mytheme = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int Theme_Mytheme_Widget = 2131099660;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
